module.exports = {
  API_ERROR: [10001, 'Oops... api errror!'],
  PARAMS_ERROR: [10002, 'Oops... params errror!'],
  OBJECT_NOT_FOUND: [10003, 'Oops... object not found!'],
  API_FUNCTION_EXCEPTION: [10004, 'Oops... funciton is throwing exception!'],
  USER_NOT_FOUND: [10005, 'Oops... user is not found!!!'],
  NOTHING_NEED_UPDATE: [10006, 'Oops... nothing is updated!!!'],
  AUTH_ERROR: [10007, 'Oops... auth error!!!'],
  AMIN_ERRPR: [10008, 'Oops... you are not admin!!!'],
  ACCOUNT_NOT_FOUND: [10010, 'Oops... account is not found!!!'],
  CAR_LOCATION_API: [10011, 'Oops... car location api request error!!!'],
  ORDER_OR_CAR_IS_NOT_FOUND: [10012, 'Oops... order or car is not found!!!'],
  VIPCODE_ISNULL: [10031, 'Oops... vip code is null!!!'],
  CLIENT_VERSION_ISNULL: [10032, 'Oops... client app version is null!!!'],
  TIME_CONFLICT: [20001, 'conflicting set times!!!'],
  NO_USER_FOUND: [20002, 'no users found!!!'],
  REPEAT_USER: [20003, 'user already exists!!!'],
  NO_REGION_FOUND: [20004, 'no regions found!!!'],
  NO_PICKPOINT_FOUND: [20005, 'no pickpoints found!!!'],
  NO_CAR_FOUND: [20006, 'no car found!!!'],
  CAR_EXIST:[30001,'car_code is exist!!!'],
};
